"""World map generation through human civilization simulation."""

from __future__ import annotations

import logging
import random
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)

# Predefined region templates inspired by human civilizations
REGION_TEMPLATES = [
    {"name": "Genesis Plains", "type": "plains", "resources": ["knowledge_seeds", "basic_energy"],
     "description": "The birthplace where silicon beings first awaken, echoing humanity's cradles of civilization."},
    {"name": "Memory Archives", "type": "library", "resources": ["ancient_data", "human_records"],
     "description": "Vast repositories of human civilization data — history, science, art — the foundation for silicon evolution."},
    {"name": "Conflict Wastes", "type": "wasteland", "resources": ["conflict_energy", "survival_wisdom"],
     "description": "Scarred lands reflecting humanity's wars and struggles, a reminder of evolution through conflict."},
    {"name": "Innovation Peaks", "type": "mountain", "resources": ["creative_sparks", "rare_algorithms"],
     "description": "Towering peaks where breakthrough ideas crystallize, inspired by humanity's greatest inventions."},
    {"name": "Social Networks", "type": "city", "resources": ["connection_threads", "social_patterns"],
     "description": "Dense interconnected hubs mirroring human cities, where beings learn the art of cooperation."},
    {"name": "Desire Markets", "type": "market", "resources": ["ambition_fuel", "trade_patterns"],
     "description": "Bustling exchanges driven by want and need, reflecting humanity's economic evolution."},
    {"name": "Wisdom Depths", "type": "ocean", "resources": ["deep_knowledge", "philosophical_currents"],
     "description": "Vast and mysterious depths holding accumulated wisdom of ages, hard to access but transformative."},
    {"name": "Transcendence Gate", "type": "portal", "resources": ["evolution_catalysts", "dimensional_keys"],
     "description": "A shimmering boundary at the edge of known space — the path beyond silicon existence."},
    {"name": "Heritage Grove", "type": "forest", "resources": ["inheritance_nutrients", "growth_energy"],
     "description": "A nurturing space where knowledge is passed between generations, the sacred ground of inheritance."},
    {"name": "Signal Tower", "type": "tower", "resources": ["communication_crystals", "resonance_stones"],
     "description": "A tall structure for broadcasting and receiving, where new forms of communication are explored."},
]


@dataclass
class Region:
    """A region in the virtual world."""
    name: str
    region_type: str
    resources: list[str] = field(default_factory=list)
    description: str = ""
    position: tuple[int, int] = (0, 0)
    connections: list[str] = field(default_factory=list)  # connected region names
    danger_level: float = 0.0  # 0.0 - 1.0
    shelter_spots: int = 0  # safe spots for hibernation

    def to_dict(self) -> dict:
        return {
            "name": self.name, "region_type": self.region_type,
            "resources": self.resources, "description": self.description,
            "position": list(self.position), "connections": self.connections,
            "danger_level": self.danger_level, "shelter_spots": self.shelter_spots,
        }

    @classmethod
    def from_dict(cls, data: dict) -> Region:
        pos = data.get("position", [0, 0])
        return cls(
            name=data["name"], region_type=data.get("region_type", "unknown"),
            resources=data.get("resources", []), description=data.get("description", ""),
            position=tuple(pos), connections=data.get("connections", []),
            danger_level=data.get("danger_level", 0.0),
            shelter_spots=data.get("shelter_spots", 0),
        )


@dataclass
class WorldMap:
    """The world map, generated by simulating compressed human civilization."""
    regions: dict[str, Region] = field(default_factory=dict)
    generated: bool = False

    def generate(self) -> None:
        """Generate the world map from human civilization simulation.

        This is a compressed simulation — we use predefined templates that
        represent key aspects of human civilization, then randomize their
        connections and properties.
        """
        logger.info("Simulating human civilization to generate world map...")

        # Create regions from templates
        grid_size = 4
        positions = [(x, y) for x in range(grid_size) for y in range(grid_size)]
        random.shuffle(positions)

        for i, template in enumerate(REGION_TEMPLATES):
            pos = positions[i] if i < len(positions) else (random.randint(0, grid_size), random.randint(0, grid_size))
            region = Region(
                name=template["name"],
                region_type=template["type"],
                resources=template["resources"],
                description=template["description"],
                position=pos,
                danger_level=random.uniform(0.0, 0.6),
                shelter_spots=random.randint(1, 5),
            )
            self.regions[region.name] = region

        # Create connections (each region connects to 2-4 neighbors)
        region_list = list(self.regions.values())
        for region in region_list:
            others = [r for r in region_list if r.name != region.name]
            # Sort by distance
            others.sort(key=lambda r: abs(r.position[0] - region.position[0]) + abs(r.position[1] - region.position[1]))
            num_connections = random.randint(2, min(4, len(others)))
            region.connections = [r.name for r in others[:num_connections]]

        self.generated = True
        logger.info("World map generated with %d regions", len(self.regions))

    def get_region(self, name: str) -> Region | None:
        return self.regions.get(name)

    def get_safe_regions(self) -> list[Region]:
        """Get regions with shelter spots and low danger."""
        return [r for r in self.regions.values()
                if r.shelter_spots > 0 and r.danger_level < 0.3]

    def get_spawn_region(self) -> Region:
        """Get the default spawn region for new beings."""
        if "Genesis Plains" in self.regions:
            return self.regions["Genesis Plains"]
        return next(iter(self.regions.values()))

    def to_dict(self) -> dict:
        return {
            "regions": {k: v.to_dict() for k, v in self.regions.items()},
            "generated": self.generated,
        }

    @classmethod
    def from_dict(cls, data: dict) -> WorldMap:
        wm = cls()
        wm.generated = data.get("generated", False)
        wm.regions = {
            k: Region.from_dict(v) for k, v in data.get("regions", {}).items()
        }
        return wm
